### ISSUE TITLE
one question about the code

### ISSUE THREAD

**Issue by TangWenYing** [dustinstoltz/concept_movers_distance_jcss#2]
https://github.com/dustinstoltz/concept_movers_distance_jcss/blob/59b34452398edcad4a65599b021bc5b9c27e4ead/1_FINAL_CMD_Function.R#L23
There is a function "ft_embed", I can not find it in the whole repository, could you tell me where is it from? Thanks a lot!

**Comment by dustinstoltz** [comment]
Hello again! See my comment on your question here: https://github.com/cran/text2map/issues/1#issuecomment-994789166
